// PUBLIC DOMAIN NOTICE
//
// This file is part of afni-core, which was written by employees of the United
// States Government (National Institutes of Health) as part of their official
// duties. It is a "United States Government Work" (17 U.S.C. 105) and is in the
// public domain; outside the US, rights are waived under CC0 1.0. See LICENSE.
//
// ---------------------------------------------------------------------------
// WHAT THIS FILE IS
//
// Conformance of `afni_core::calc` against AFNI's expression evaluator
// (parser.f, reached through `1deval`). Expected values live in
// tests/data/conformance/calc.ref, generated by
// tests/data/regenerate_calc_refs.sh. With AFNI_CORE_LIVE=1 every case is also
// re-run through the live `1deval`.
//
// Each case is `<expression> [letter=number ...] => <value>`. `1deval` prints
// 6 significant digits, so values are compared to 2e-5 relative.
// ---------------------------------------------------------------------------

mod common;

use afni_core::calc::Expr;
use common::{assert_close, live_enabled, run_afni, Fixture, Tolerance};

const FIXTURE: &str = "conformance/calc.ref";

/// Evaluate a fixture case with afni-core.
fn evaluate(args: &[String]) -> f64 {
    let expr = Expr::parse(&args[0]).unwrap_or_else(|e| panic!("{}: {e}", args[0]));
    let assigned: Vec<(char, f64)> = args[1..]
        .iter()
        .map(|a| {
            let (name, value) = a.split_once('=').expect("letter=number");
            (name.chars().next().unwrap(), value.parse().unwrap())
        })
        .collect();
    expr.eval(|c| {
        assigned
            .iter()
            .find(|(n, _)| *n == c)
            .map_or(0.0, |(_, v)| *v)
    })
}

#[test]
fn fixture_records_afni_provenance_and_has_many_cases() {
    let fx = Fixture::load(FIXTURE);
    assert!(fx.afni_version().contains("AFNI_"));
    assert!(fx.cases.len() > 150, "{} cases", fx.cases.len());
}

#[test]
fn every_case_matches_afni() {
    let fx = Fixture::load(FIXTURE);
    let tol = Tolerance {
        abs: 1e-6,
        rel: 2e-5,
    };
    for case in &fx.cases {
        let label = format!("line {}: {}", case.line, case.args.join(" "));
        assert_close(&label, evaluate(&case.args), case.expected, tol);
    }
}

#[test]
fn every_case_matches_live_afni() {
    if !live_enabled() {
        return;
    }
    let fx = Fixture::load(FIXTURE);
    let tol = Tolerance {
        abs: 1e-6,
        rel: 2e-5,
    };
    for case in &fx.cases {
        let mut args: Vec<String> = case.args[1..].iter().map(|a| format!("-{a}")).collect();
        args.extend([
            "-num".into(),
            "1".into(),
            "-expr".into(),
            case.args[0].clone(),
        ]);
        let out = run_afni("1deval", &args).expect("1deval");
        let live: f64 = out.trim().lines().last().unwrap().trim().parse().unwrap();
        assert_close(
            &format!("live line {}", case.line),
            live,
            case.expected,
            tol,
        );
        assert_close(
            &format!("afni-core line {}", case.line),
            evaluate(&case.args),
            live,
            tol,
        );
    }
}
