// PUBLIC DOMAIN NOTICE
//
// This file is part of afni-core, which was written by employees of the United
// States Government (National Institutes of Health) as part of their official
// duties. It is a "United States Government Work" (17 U.S.C. 105) and is in the
// public domain; outside the US, rights are waived under CC0 1.0. See LICENSE.
//
// ---------------------------------------------------------------------------
// WHAT THIS FILE IS
//
// Conformance of `afni_core::afni_colors` against AFNI's own display.c code.
// tests/data/conformance/afni_colorscales.ref holds every entry of all nine
// built-in scales (at five sizes: 256 is AFNI's default) and direct samples of
// DC_spectrum_AJJ / DC_spectrum_ZSS, generated by
// tests/data/regenerate_afni_colorscales.sh from AFNI's source functions.
// The comparison is EXACT (bytes), not approximate.
// ---------------------------------------------------------------------------

mod common;

use afni_core::afni_colors::{spectrum_ajj, spectrum_zss, AfniColorScale};

const FIXTURE: &str = "conformance/afni_colorscales.ref";

fn lines() -> Vec<String> {
    std::fs::read_to_string(common::data(FIXTURE))
        .unwrap()
        .lines()
        .map(str::to_owned)
        .collect()
}

fn parse_rgb(text: &str) -> [u8; 3] {
    let v: Vec<u8> = text.split(',').map(|n| n.parse().unwrap()).collect();
    [v[0], v[1], v[2]]
}

#[test]
fn fixture_records_provenance() {
    let head: Vec<String> = lines().into_iter().filter(|l| l.starts_with('#')).collect();
    assert!(head
        .iter()
        .any(|l| l.contains("afni_version: ") && l.contains("AFNI_")));
    assert!(head.iter().any(|l| l.contains("afni_source_commit")));
}

#[test]
fn every_entry_of_every_builtin_scale_matches_afni_exactly() {
    let mut compared = 0;
    let mut sizes = std::collections::BTreeSet::new();
    for line in lines().iter().filter(|l| l.starts_with("scale ")) {
        // "scale <n> <name> : r,g,b r,g,b ..."
        let (head, body) = line.split_once(" : ").unwrap();
        let mut head = head.split_whitespace().skip(1);
        let n: usize = head.next().unwrap().parse().unwrap();
        let name = head.next().unwrap();
        let theirs: Vec<[u8; 3]> = body.split_whitespace().map(parse_rgb).collect();
        assert_eq!(theirs.len(), n, "{name} at {n}");

        let scale = AfniColorScale::from_name(name)
            .unwrap_or_else(|| panic!("AFNI scale {name:?} is unknown to afni-core"));
        let ours = scale.table(n).unwrap();
        for (i, (a, b)) in ours.iter().zip(&theirs).enumerate() {
            assert_eq!(
                a, b,
                "{name} (n = {n}) entry {i}: afni-core {a:?}, AFNI {b:?}"
            );
        }
        sizes.insert(n);
        compared += 1;
    }
    // Nine scales at each of five sizes, and 256 (AFNI's default) among them.
    assert_eq!(compared, 9 * 5);
    assert!(sizes.contains(&256) && sizes.len() == 5);
}

#[test]
fn afni_defines_exactly_the_scales_afni_core_knows() {
    let from_afni: std::collections::BTreeSet<String> = lines()
        .iter()
        .filter(|l| l.starts_with("scale "))
        .map(|l| l.split_whitespace().nth(2).unwrap().to_owned())
        .collect();
    let ours: std::collections::BTreeSet<String> = AfniColorScale::ALL
        .iter()
        .map(|s| s.name().to_owned())
        .collect();
    assert_eq!(from_afni, ours);
}

#[test]
fn spectrum_functions_match_afni_including_wrap_and_gamma_edge_cases() {
    let mut compared = 0;
    for line in lines().iter().filter(|l| l.starts_with("spec ")) {
        // "spec AJJ <hue> <gamma> : r,g,b"
        let (head, rgb) = line.split_once(" : ").unwrap();
        let w: Vec<&str> = head.split_whitespace().collect();
        let (which, hue, gamma): (&str, f64, f64) =
            (w[1], w[2].parse().unwrap(), w[3].parse().unwrap());
        let ours = match which {
            "AJJ" => spectrum_ajj(hue, gamma),
            "ZSS" => spectrum_zss(hue, gamma),
            other => panic!("unknown function {other}"),
        };
        assert_eq!(ours, parse_rgb(rgb), "{which}({hue}, {gamma})");
        compared += 1;
    }
    assert_eq!(compared, 220);
}
