// PUBLIC DOMAIN NOTICE
//
// This file is part of afni-core, which was written by employees of the United
// States Government (National Institutes of Health) as part of their official
// duties. It is a "United States Government Work" (17 U.S.C. 105) and is in the
// public domain; outside the US, rights are waived under CC0 1.0. See LICENSE.
//
// ---------------------------------------------------------------------------
// WHAT THIS FILE IS
//
// Conformance of `afni_core::topology` and `afni_core::mesh` against SUMA:
// triangle areas, node areas, triangle and node normals, edge lists, and
// boundary nodes, as written by `SurfaceMetrics` and `SurfMeasures` for the
// committed meshes `irr2` (an irregular closed sphere) and `patch2` (an open
// piece of it). Generated by tests/data/regenerate_surface_refs.sh.
//
// SUMA computes in single precision and prints six decimals, so the tolerances
// below are those of the reference, not of afni-core.
// ---------------------------------------------------------------------------

mod common;

use afni_core::mesh::{Orientation, SurfaceMesh};

fn mesh(name: &str) -> SurfaceMesh {
    let (v, f) = common::read_asc(name);
    SurfaceMesh::from_triangles(v, f).unwrap()
}

fn close(a: f64, b: f64, abs: f64, rel: f64) -> bool {
    (a - b).abs() <= abs + rel * b.abs()
}

fn unit_from_segment(row: &[f64]) -> [f64; 3] {
    // Columns 0-2 are the start point, 3-5 a point 5 units along the normal.
    let d = [row[3] - row[0], row[4] - row[1], row[5] - row[2]];
    let n = (d[0] * d[0] + d[1] * d[1] + d[2] * d[2]).sqrt();
    [d[0] / n, d[1] / n, d[2] / n]
}

#[test]
fn triangle_areas_match_surface_metrics() {
    for name in ["irr2", "patch2"] {
        let m = mesh(name);
        let theirs = common::read_table(&format!("surfaces/refs/{name}.area"));
        assert_eq!(theirs.len(), m.topology().face_count(), "{name}");
        for (i, (ours, row)) in m.face_areas().iter().zip(&theirs).enumerate() {
            assert_eq!(row[0] as usize, i);
            assert!(
                close(*ours, row[1], 5e-5, 3e-6),
                "{name} triangle {i}: {ours} vs {}",
                row[1]
            );
        }
    }
}

#[test]
fn node_areas_match_surf_measures() {
    for name in ["irr2", "patch2"] {
        let m = mesh(name);
        let theirs = common::read_table(&format!("surfaces/refs/{name}.nodearea.1D"));
        assert_eq!(theirs.len(), m.vertices().len());
        for (i, (ours, row)) in m.node_areas().iter().zip(&theirs).enumerate() {
            assert!(
                close(*ours, row[1], 2e-5, 3e-6),
                "{name} node {i}: {ours} vs {}",
                row[1]
            );
        }
    }
}

#[test]
fn triangle_normals_match_surface_metrics() {
    for name in ["irr2", "patch2"] {
        let m = mesh(name);
        let theirs = common::read_table(&format!("surfaces/refs/{name}.TriNormSeg.1D"));
        for (i, (ours, row)) in m.face_normals().iter().zip(&theirs).enumerate() {
            let want = unit_from_segment(row);
            for k in 0..3 {
                assert!(
                    (ours[k] - want[k]).abs() < 5e-6,
                    "{name} triangle {i}: {ours:?} vs {want:?}"
                );
            }
        }
    }
}

#[test]
fn node_normals_match_surface_metrics_and_are_not_area_weighted() {
    for name in ["irr2", "patch2"] {
        let m = mesh(name);
        let theirs = common::read_table(&format!("surfaces/refs/{name}.NodeNormSeg.1D"));
        for (i, (ours, row)) in m.vertex_normals().iter().zip(&theirs).enumerate() {
            let want = unit_from_segment(row);
            for k in 0..3 {
                assert!(
                    (ours[k] - want[k]).abs() < 5e-6,
                    "{name} node {i}: {ours:?} vs {want:?}"
                );
            }
        }
    }
    // The irregular mesh really distinguishes the conventions: the area-weighted
    // normal (normalized sum of raw cross products) differs visibly from SUMA's.
    let m = mesh("irr2");
    let mut weighted = vec![[0.0_f64; 3]; m.vertices().len()];
    let v = |i: u32| m.vertices()[i as usize].map(f64::from);
    for f in m.topology().faces() {
        let (a, b, c) = (v(f[0]), v(f[1]), v(f[2]));
        let (e1, e2) = (
            [b[0] - a[0], b[1] - a[1], b[2] - a[2]],
            [c[0] - a[0], c[1] - a[1], c[2] - a[2]],
        );
        let cr = [
            e1[1] * e2[2] - e1[2] * e2[1],
            e1[2] * e2[0] - e1[0] * e2[2],
            e1[0] * e2[1] - e1[1] * e2[0],
        ];
        for &n in f {
            for k in 0..3 {
                weighted[n as usize][k] += cr[k];
            }
        }
    }
    let theirs = common::read_table("surfaces/refs/irr2.NodeNormSeg.1D");
    let worst = weighted
        .iter()
        .zip(&theirs)
        .map(|(w, row)| {
            let len = (w[0] * w[0] + w[1] * w[1] + w[2] * w[2]).sqrt();
            let want = unit_from_segment(row);
            (0..3)
                .map(|k| (w[k] / len - want[k]).abs())
                .fold(0.0, f64::max)
        })
        .fold(0.0, f64::max);
    assert!(worst > 1e-3, "area-weighted normals agree with SUMA to {worst:e}, so this test cannot tell the conventions apart");
}

#[test]
fn edges_match_surface_metrics() {
    for name in ["irr2", "patch2"] {
        let m = mesh(name);
        let theirs = common::read_table(&format!("surfaces/refs/{name}.edges"));
        // Rows: edge index, node 1, node 2, triangles on the edge, length.
        let mut want: Vec<(u32, u32, usize, f64)> = theirs
            .iter()
            .map(|r| {
                (
                    (r[1] as u32).min(r[2] as u32),
                    (r[1] as u32).max(r[2] as u32),
                    r[3] as usize,
                    r[4],
                )
            })
            .collect();
        want.sort_by_key(|e| (e.0, e.1));
        let lengths = m.edge_lengths();
        assert_eq!(m.topology().edges().len(), want.len(), "{name}: edge count");
        for (e, (len, w)) in m.topology().edges().iter().zip(lengths.iter().zip(&want)) {
            assert_eq!((e.nodes[0], e.nodes[1]), (w.0, w.1), "{name}");
            assert_eq!(
                e.faces.len(),
                w.2,
                "{name} edge {:?}: triangles on the edge",
                e.nodes
            );
            assert!(
                close(*len, w.3, 5e-5, 3e-6),
                "{name} edge {:?}: {len} vs {}",
                e.nodes,
                w.3
            );
        }
    }
}

#[test]
fn boundary_nodes_match_surface_metrics_for_an_open_patch() {
    let m = mesh("patch2");
    let theirs: Vec<u32> = common::read_table("surfaces/refs/patch2.boundarynodes")
        .iter()
        .map(|r| r[0] as u32)
        .collect();
    let report = m.topology().report();
    assert_eq!(report.boundary_nodes, theirs);
    assert!(!report.boundary_edges.is_empty());
    assert!(!report.is_closed_manifold());
    assert_eq!(report.euler_characteristic, 1, "a topological disk");
    assert_eq!(m.orientation(), Orientation::Undefined);
}

#[test]
fn the_closed_irregular_sphere_is_a_clean_outward_sphere() {
    let m = mesh("irr2");
    let report = m.topology().report();
    assert!(report.is_clean(), "{report:?}");
    assert_eq!(report.euler_characteristic, 2);
    assert_eq!(m.orientation(), Orientation::Outward);
    // SUMA writes outward normals: they point away from the centre.
    let c = m.bounds().center();
    for (i, n) in m.vertex_normals().iter().enumerate() {
        let v = m.vertices()[i];
        let radial = [
            f64::from(v[0]) - c[0],
            f64::from(v[1]) - c[1],
            f64::from(v[2]) - c[2],
        ];
        assert!(
            n[0] * radial[0] + n[1] * radial[1] + n[2] * radial[2] > 0.0,
            "node {i}"
        );
    }
    // Every node on a sphere mesh has 5 or 6 neighbors, and the node areas sum to the total.
    assert!(m
        .topology()
        .all_neighbors()
        .iter()
        .all(|l| l.len() == 5 || l.len() == 6));
    let total: f64 = m.node_areas().iter().sum();
    assert!((total - m.total_area()).abs() < 1e-9 * total);
}
