// PUBLIC DOMAIN NOTICE
//
// This file is part of afni-core, which was written by employees of the United
// States Government (National Institutes of Health) as part of their official
// duties. It is a "United States Government Work" (17 U.S.C. 105) and is in the
// public domain; outside the US, rights are waived under CC0 1.0. See LICENSE.
//
// ---------------------------------------------------------------------------
// WHAT THIS FILE IS
//
// Conformance of `afni_core::overlay` against SUMA's own value-to-color mapping,
// as run by AFNI's `ScaleToMap` program (SUMA_ScaleToMap in SUMA_Color.c).
// tests/data/conformance/scaletomap.ref holds 54 cases (four color maps by
// interpolated, banded and direct mapping, intensity clipping, auto range, mask
// ranges, the brightness factor, and a zero-width range), generated by
// tests/data/regenerate_scaletomap.sh. Each case is replayed through
// `evaluate_rows` and compared node by node; a node `ScaleToMap` masked must be
// invisible here.
//
// With AFNI_CORE_LIVE=1 the cases are also re-run through the live program.
// ---------------------------------------------------------------------------

mod common;

use afni_core::color::Rgba;
use afni_core::column::ColumnRange;
use afni_core::overlay::{
    evaluate_rows, ColorTable, FailedThreshold, OverlayColors, OverlayInputs, OverlaySpec,
    PaneRule, RangeSelection,
};
use afni_core::threshold::Threshold;

const FIXTURE: &str = "conformance/scaletomap.ref";

/// One parsed line of the fixture.
struct Case {
    name: String,
    options: Vec<String>,
    map: Vec<[f32; 3]>,
    values: Vec<f64>,
    /// Node index to RGB, for the nodes ScaleToMap did NOT mask.
    expected: Vec<(usize, [f64; 3])>,
}

fn parse_cases() -> Vec<Case> {
    let text = std::fs::read_to_string(common::data(FIXTURE)).unwrap();
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|line| {
            let (lhs, rhs) = line.split_once("=>").unwrap();
            let fields: Vec<&str> = lhs.split(" | ").map(str::trim).collect();
            let map = fields[2]
                .split_whitespace()
                .map(|c| {
                    let v: Vec<f32> = c.split(',').map(|x| x.parse().unwrap()).collect();
                    [v[0], v[1], v[2]]
                })
                .collect();
            let expected = rhs
                .split_whitespace()
                .map(|e| {
                    let (node, rgb) = e.split_once(':').unwrap();
                    let v: Vec<f64> = rgb.split(',').map(|x| x.parse().unwrap()).collect();
                    (node.parse().unwrap(), [v[0], v[1], v[2]])
                })
                .collect();
            Case {
                name: fields[0].to_owned(),
                options: fields[1].split_whitespace().map(str::to_owned).collect(),
                map,
                values: fields[3]
                    .split_whitespace()
                    .map(|v| v.parse().unwrap())
                    .collect(),
                expected,
            }
        })
        .collect()
}

/// The overlay spec equivalent to a set of `ScaleToMap` options.
fn spec_for(case: &Case) -> OverlaySpec {
    let table = ColorTable::new(
        case.map
            .iter()
            .map(|&[r, g, b]| Rgba { r, g, b, a: 1.0 })
            .collect(),
    )
    .unwrap();
    let mut rule = PaneRule::SumaInterpolated; // -interp is ScaleToMap's default
    let mut range = RangeSelection::Computed;
    let mut spec_brightness = 1.0_f32;
    let mut mask: Option<(f64, f64)> = None;
    let mut it = case.options.iter();
    while let Some(opt) = it.next() {
        let mut num = || -> f64 { it.next().expect("option value").parse().unwrap() };
        match opt.as_str() {
            "-interp" => rule = PaneRule::SumaInterpolated,
            "-nointerp" => rule = PaneRule::SumaBanded,
            "-direct" => rule = PaneRule::Direct,
            "-clp" => {
                let (a, b) = (num(), num());
                range = RangeSelection::Manual(ColumnRange::new(a, b).unwrap());
            }
            "-apr" => range = RangeSelection::Manual(ColumnRange::new(0.0, num()).unwrap()),
            "-msk" => mask = Some((num(), num())),
            "-br" => spec_brightness = num() as f32,
            other => panic!("{}: unhandled option {other}", case.name),
        }
    }
    let mut spec = OverlaySpec::new(OverlayColors::Panes { table, rule });
    spec.intensity_range = range;
    // ScaleToMap masks exact zeros unless told otherwise.
    spec.show_zero = false;
    spec.colormap_brightness = spec_brightness;
    if let Some((lo, hi)) = mask {
        // SUMA hides values INSIDE [lo, hi], ends included: that is `Outside`, whose
        // ends fail.
        spec.threshold = Threshold::Outside { lo, hi };
        spec.failed = FailedThreshold::Hide;
    }
    spec
}

fn compare(case: &Case, evaluation_colors: &[Rgba], expected: &[(usize, [f64; 3])]) {
    let visible: Vec<usize> = evaluation_colors
        .iter()
        .enumerate()
        .filter(|(_, c)| c.a > 0.0)
        .map(|(i, _)| i)
        .collect();
    let wanted: Vec<usize> = expected.iter().map(|e| e.0).collect();
    assert_eq!(
        visible, wanted,
        "{}: which nodes are drawn (the rest are masked)",
        case.name
    );
    for &(node, rgb) in expected {
        let got = evaluation_colors[node];
        for (channel, (g, w)) in [got.r, got.g, got.b].iter().zip(rgb).enumerate() {
            // ScaleToMap prints six decimals.
            assert!(
                (f64::from(*g) - w).abs() <= 2.0e-6,
                "{} node {node} (value {}) channel {channel}: afni-core {g}, SUMA {w}",
                case.name,
                case.values[node]
            );
        }
        assert_eq!(got.a, 1.0, "{} node {node}", case.name);
    }
}

/// One output line of `ScaleToMap`: `node r g b`, or `None` for anything else.
fn parse_output_line(line: &str) -> Option<(usize, [f64; 3])> {
    let w: Vec<&str> = line.split_whitespace().collect();
    if w.len() != 4 {
        return None;
    }
    let node = w[0].parse().ok()?;
    Some((
        node,
        [w[1].parse().ok()?, w[2].parse().ok()?, w[3].parse().ok()?],
    ))
}

#[test]
fn matches_suma_scale_to_map_node_by_node() {
    let cases = parse_cases();
    assert_eq!(cases.len(), 54);
    let mut nodes = 0;
    for case in &cases {
        let spec = spec_for(case);
        let evaluation = evaluate_rows(
            &spec,
            &OverlayInputs {
                intensity: &case.values,
                ..Default::default()
            },
        )
        .unwrap_or_else(|e| panic!("{}: {e}", case.name));
        compare(case, &evaluation.colors, &case.expected);
        nodes += case.expected.len();
    }
    assert!(nodes > 400, "only {nodes} node colors were compared");
}

#[test]
fn the_cases_exercise_every_mode_and_option() {
    let cases = parse_cases();
    for needle in [
        "interp_unit",
        "nointerp_unit",
        "clip_narrow",
        "apr_",
        "autorange_",
        "mask_range",
        "bright_half",
        "bright_quarter",
        "combo_",
        "direct_",
        "flat_range",
    ] {
        assert!(
            cases.iter().any(|c| c.name.starts_with(needle)),
            "no case named {needle}*"
        );
    }
    // Masking really removes nodes in the reference (so the visibility check bites).
    let masked = cases.iter().find(|c| c.name == "mask_range_M5").unwrap();
    assert!(masked.expected.len() < masked.values.len());
}

#[test]
fn live_scale_to_map_agrees_with_the_committed_cases() {
    if !common::live_enabled() {
        eprintln!("skipping: set AFNI_CORE_LIVE=1 to re-run ScaleToMap");
        return;
    }
    let dir = std::env::temp_dir().join(format!("afni_core_scaletomap_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    for case in parse_cases() {
        let map_file = dir.join("map.1D");
        let val_file = dir.join("val.1D");
        let map_text: String = case
            .map
            .iter()
            .map(|[r, g, b]| format!("{r} {g} {b}\n"))
            .collect();
        let val_text: String = case.values.iter().map(|v| format!("{v}\n")).collect();
        std::fs::write(&map_file, map_text).unwrap();
        std::fs::write(&val_file, val_text).unwrap();
        let mut args: Vec<String> = [
            "-input",
            val_file.to_str().unwrap(),
            "-1",
            "0",
            "-cmapfile",
            map_file.to_str().unwrap(),
            "-frf",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        args.extend(case.options.iter().cloned());
        args.push("-nomsk_col".into());
        let out = common::run_afni("ScaleToMap", &args).unwrap();
        let live: Vec<(usize, [f64; 3])> = out.lines().filter_map(parse_output_line).collect();
        assert_eq!(
            live, case.expected,
            "{}: live ScaleToMap differs from the committed case",
            case.name
        );
    }
    let _ = std::fs::remove_dir_all(dir);
}
