// PUBLIC DOMAIN NOTICE
//
// This file is part of afni-core, which was written by employees of the United
// States Government (National Institutes of Health) as part of their official
// duties. It is a "United States Government Work" (17 U.S.C. 105) and is in the
// public domain; outside the US, rights are waived under CC0 1.0. See LICENSE.
//
// ---------------------------------------------------------------------------
// WHAT THIS FILE IS
//
// Conformance of `afni_core::stats` against AFNI's own statistical library
// (NIfTI `nifticdf.c`, the code `p2dsetstat`, `3dcalc` and friends use).
// Expected values live in tests/data/conformance/nifti_stats.ref, generated by
// tests/data/regenerate_nifti_stats.sh from AFNI's source at full precision.
// Also checks the older `cdf` program's two-sided conventions
// (conformance/cdf.ref) and, with AFNI_CORE_LIVE=1, the live `cdf`, `ccalc`
// and `p2dsetstat` programs.
//
// HOW IT RELATES TO THE REST OF THE CRATE
//
// Uses the shared harness in tests/common/mod.rs. Documents every place where
// afni-core deliberately differs from AFNI (see "KNOWN DEPARTURES" below).
//
// KNOWN DEPARTURES (intentional; each is also in the roadmap discovery log)
//
//  * Discrete distributions (binomial, Poisson): AFNI/CDFLIB evaluate a
//    continuous extension at non-integer statistics; afni-core uses the true
//    step function. Compared here only at integer statistics. Inverses are
//    integer quantiles, so they are not compared with AFNI's real-valued roots.
//  * AFNI's correl_p2t returns 0 when nort < 1; afni-core accepts nort >= 0.
//  * AFNI's CDFLIB inverse is only good to ~1e-8 absolute (for example
//    `-1 0.5 CORREL 18` gives -5.0e-9 where the exact answer is 0), so inverses
//    are compared with an absolute tolerance of 5e-8.
//  * AFNI's uniform q = 1 - u is outside [0, 1] when the statistic is outside
//    the support (e.g. 1.25); afni-core clamps to the valid probability.
//  * AFNI returns sentinels (0, -1, 99.99, 1.0) on error; afni-core errors.
// ---------------------------------------------------------------------------

mod common;

use afni_core::stat::{IntentOrigin, StatKind, StatSpec};
use afni_core::stats::{critical_value, p_value, Tail};
use common::{is_close, Fixture, Tolerance};

/// NIfTI intent names used in the fixture -> AFNI/NIfTI stat codes.
fn code_for(name: &str) -> i64 {
    match name {
        "CORREL" => 2,
        "TTEST" => 3,
        "FTEST" => 4,
        "ZSCORE" => 5,
        "CHISQ" => 6,
        "BETA" => 7,
        "BINOM" => 8,
        "GAMMA" => 9,
        "POISSON" => 10,
        "NORMAL" => 11,
        "FTEST_NONC" => 12,
        "CHISQ_NONC" => 13,
        "TTEST_NONC" => 17,
        "LOGISTIC" => 14,
        "LAPLACE" => 15,
        "UNIFORM" => 16,
        "WEIBULL" => 18,
        "CHI" => 19,
        "INVGAUSS" => 20,
        "EXTVAL" => 21,
        other => panic!("unknown code {other}"),
    }
}

/// Which AFNI operation a fixture line performs.
#[derive(Debug, PartialEq)]
enum Op {
    /// `P(X <= val)`.
    Cdf,
    /// `P(X > val)`.
    Upper,
    /// `x` with `P(X <= x) = val`.
    Inverse,
}

struct Parsed {
    op: Op,
    value: f64,
    spec: StatSpec,
    discrete: bool,
}

fn parse(args: &[String]) -> Parsed {
    let (op, rest) = match args[0].as_str() {
        "-q" => (Op::Upper, &args[1..]),
        "-1" => (Op::Inverse, &args[1..]),
        _ => (Op::Cdf, args),
    };
    let value: f64 = rest[0].parse().unwrap();
    let code = code_for(&rest[1]);
    let mut p = [0.0; 3];
    for (slot, text) in p.iter_mut().zip(&rest[2..]) {
        *slot = text.parse().unwrap();
    }
    // The fixture uses NIfTI parameters, so CORREL carries a single dof.
    let spec = StatSpec::from_intent(code, p, IntentOrigin::Standard)
        .unwrap()
        .unwrap();
    Parsed {
        op,
        value,
        discrete: matches!(spec.kind, StatKind::Binom | StatKind::Poisson),
        spec,
    }
}

/// Relative tolerance for CDFLIB-derived reference values.
const TOL: Tolerance = Tolerance {
    abs: 1e-300,
    rel: 1e-8,
};

/// Probabilities this small are at the edge of what CDFLIB resolves; compare
/// them in log space instead.
const TINY: f64 = 1e-290;

/// AFNI's CDFLIB `cumchn` and `cumfnc` (noncentral chi-square and F) stop their
/// series at an internal tolerance of about 1e-5, and the printed tails are
/// differences of such sums, so they are only good to ~1e-5 ABSOLUTE (worst observed 1e-5; e.g. for
/// `F(3,20; 2)` at 3 AFNI gives 0.8237480 where an independent summation and
/// afni-core both give 0.8237555); they are
/// the less accurate side of this comparison. (Noncentral t agrees to ~2e-10 and
/// uses the ordinary tolerance.) The exact values are cross-checked independently
/// in `stats::tests`.
const CDFLIB_NONCENTRAL_TOL: Tolerance = Tolerance {
    abs: 2e-5,
    rel: 1e-6,
};

/// The CDFLIB-limited noncentral kinds.
fn is_cdflib_noncentral(kind: StatKind) -> bool {
    matches!(kind, StatKind::FtestNonc | StatKind::ChisqNonc)
}

#[test]
fn fixture_records_provenance() {
    let fx = Fixture::load("conformance/nifti_stats.ref");
    assert!(fx.afni_version().contains("AFNI_"));
    assert!(fx.provenance.contains_key("afni_source_commit"));
    assert!(fx.cases.len() > 300);
}

#[test]
fn matches_afni_nifticdf_forward_and_inverse() {
    let fx = Fixture::load("conformance/nifti_stats.ref");
    let mut checked = 0;
    for case in &fx.cases {
        let label = format!("line {}: {}", case.line, case.args.join(" "));
        let c = parse(&case.args);
        match c.op {
            Op::Cdf | Op::Upper => {
                let tail = if c.op == Op::Cdf {
                    Tail::Lower
                } else {
                    Tail::Upper
                };
                // Where AFNI evaluated a continuous extension, only integer
                // statistics are comparable (see KNOWN DEPARTURES).
                if c.discrete && c.value.fract() != 0.0 {
                    continue;
                }
                let got =
                    p_value(&c.spec, c.value, tail).unwrap_or_else(|e| panic!("{label}: {e}"));
                // AFNI's uniform reports q = 1 - u outside its support, giving
                // "probabilities" above 1 or below 0 (see KNOWN DEPARTURES).
                // Ours is clamped to the valid range; check that and move on.
                if !(0.0..=1.0).contains(&case.expected) {
                    assert_eq!(c.spec.kind, StatKind::Uniform, "{label}");
                    assert_eq!(got.p(), case.expected.clamp(0.0, 1.0), "{label}");
                    checked += 1;
                    continue;
                }
                // CDFLIB's 'p' and 'q' are only good to its absolute accuracy
                // (~1e-12) when they are the *large* tail; compare small ones
                // relatively and large ones absolutely.
                let tol = if is_cdflib_noncentral(c.spec.kind) {
                    CDFLIB_NONCENTRAL_TOL
                } else if case.expected < 0.5 {
                    TOL
                } else {
                    Tolerance {
                        abs: 1e-12,
                        rel: 1e-9,
                    }
                };
                if case.expected < TINY {
                    // Underflow region: require it to be tiny too.
                    assert!(got.p() < 1e-280, "{label}: expected ~0, got {}", got.p());
                } else {
                    common::assert_close(&label, got.p(), case.expected, tol);
                }
            }
            Op::Inverse => {
                assert!(
                    !c.discrete,
                    "{label}: discrete inverses are not in the fixture"
                );
                let got = critical_value(&c.spec, c.value, Tail::Lower)
                    .unwrap_or_else(|e| panic!("{label}: {e}"));
                // CDFLIB's noncentral chi-square/F inverses inherit its ~1e-5 absolute
                // error in p, which is a percent-level error in x far in the tail.
                // Compare loosely with AFNI, and check our own inverse exactly by
                // feeding it back through the forward function.
                let tol = if is_cdflib_noncentral(c.spec.kind) {
                    Tolerance {
                        abs: 1e-3,
                        rel: 1e-2,
                    }
                } else {
                    Tolerance {
                        abs: 5e-8,
                        rel: 1e-7,
                    }
                };
                let back = p_value(&c.spec, got, Tail::Lower).unwrap().p();
                common::assert_close(
                    &format!("{label} (round trip)"),
                    back,
                    c.value,
                    Tolerance {
                        abs: 1e-14,
                        rel: 1e-8,
                    },
                );
                common::assert_close(&label, got, case.expected, tol);
            }
        }
        checked += 1;
    }
    assert!(checked > 250, "only {checked} cases were comparable");
}

#[test]
fn two_sided_conventions_match_the_cdf_program() {
    // conformance/cdf.ref holds AFNI's `cdf -t2p/-p2t`, which is TWO-SIDED for
    // fizt/fitt and UPPER-TAIL for fift/fict (see the roadmap discovery log).
    // Compare with six-digit tolerance.
    let fx = Fixture::load("conformance/cdf.ref");
    let mut checked = 0;
    for case in &fx.cases {
        let label = format!("cdf.ref line {}: {}", case.line, case.args.join(" "));
        let a: Vec<&str> = case.args.iter().map(String::as_str).collect();
        let num = |i: usize| -> f64 { a[i].parse().unwrap() };
        let (mode, name) = (a[0], a[1]);
        let (kind, params, tail) = match name {
            "fizt" => (StatKind::Zscore, vec![], Tail::TwoSided),
            "fitt" => (StatKind::Ttest, vec![num(3)], Tail::TwoSided),
            "fift" => (StatKind::Ftest, vec![num(3), num(4)], Tail::Upper),
            "fict" => (StatKind::Chisq, vec![num(3)], Tail::Upper),
            other => panic!("{label}: unexpected {other}"),
        };
        let spec = StatSpec::new(kind, &params, 0.0);
        let x = num(2);
        if mode == "-t2p" {
            let got = p_value(&spec, x, tail).unwrap().p();
            common::assert_close(&label, got, case.expected, Tolerance::SIX_DIGITS);
        } else {
            // -p2t: AFNI's argument is the probability for the same tail rule.
            let got = critical_value(&spec, x, tail).unwrap();
            common::assert_close(&label, got, case.expected, Tolerance::SIX_DIGITS);
        }
        checked += 1;
    }
    assert!(checked >= 15);
}

#[test]
fn matches_afni_threshold_and_p_value_programs_when_live() {
    if !common::live_enabled() {
        eprintln!("skipping: set AFNI_CORE_LIVE=1 to compare with live AFNI");
        return;
    }
    // `ccalc` exposes AFNI's own `*_t2p` conversions (mri_stats.c): fitt/fico
    // are two-sided for signed statistics, fift/fict upper-tail.
    let ccalc = |expr: &str| -> f64 {
        let out = common::run_afni("ccalc", &["-eval".into(), expr.into()]).expect("ccalc");
        out.trim()
            .parse()
            .unwrap_or_else(|_| panic!("ccalc {expr}: {out:?}"))
    };
    let check = |label: &str, got: f64, want: f64| {
        // `ccalc` prints six DECIMAL places (0.003979 for 0.0039787), so small
        // probabilities are only good to an absolute 5e-7.
        let tol = Tolerance {
            abs: 5.1e-7,
            rel: 5.5e-6,
        };
        assert!(is_close(got, want, tol), "{label}: {got} vs {want}");
    };
    let t = StatSpec::new(StatKind::Ttest, &[23.0], 0.0);
    let f = StatSpec::new(StatKind::Ftest, &[2.0, 40.0], 0.0);
    let chi = StatSpec::new(StatKind::Chisq, &[5.0], 0.0);
    let simple = StatSpec::new(StatKind::Correl, &[25.0, 1.0, 1.0], 0.0);
    let multiple = StatSpec::new(StatKind::Correl, &[30.0, 2.0, 1.0], 0.0);
    for x in [0.5, 1.7, 3.2] {
        check(
            "t",
            p_value(&t, x, Tail::TwoSided).unwrap().p(),
            ccalc(&format!("fitt_t2p({x},23)")),
        );
        check(
            "F",
            p_value(&f, x, Tail::Upper).unwrap().p(),
            ccalc(&format!("fift_t2p({x},2,40)")),
        );
        check(
            "chisq",
            p_value(&chi, x, Tail::Upper).unwrap().p(),
            ccalc(&format!("fict_t2p({x},5)")),
        );
    }
    for r in [0.1, 0.4, 0.8] {
        check(
            "r (nfit=1)",
            p_value(&simple, r, Tail::TwoSided).unwrap().p(),
            ccalc(&format!("fico_t2p({r},25,1,1)")),
        );
        check(
            "R (nfit=2)",
            p_value(&multiple, r, Tail::Upper).unwrap().p(),
            ccalc(&format!("fico_t2p({r},30,2,1)")),
        );
    }
    check(
        "t inverse",
        critical_value(&t, 0.05, Tail::TwoSided).unwrap(),
        ccalc("fitt_p2t(0.05,23)"),
    );
}

/// Threshold values printed by AFNI's `p2dsetstat` (AFNI_26.2.08) for the
/// committed afni-io volumes `stat+orig` (Ttest(23), Ftest(2,40)) and
/// `correl+orig` (Correl(30,2,1)). Each row: dataset, sub-brick, the
/// `p2dsetstat` sidedness flag, the p given to it, and the threshold it printed.
const P2DSETSTAT: &[(&str, usize, &str, f64, f64)] = &[
    ("stat+orig", 0, "-2sided", 0.01, 2.807336),
    ("stat+orig", 0, "-1sided", 0.01, 2.499867),
    ("stat+orig", 1, "-1sided", 0.01, 5.178508),
    ("correl+orig", 0, "-2sided", 0.01, 0.537614),
    ("correl+orig", 0, "-1sided", 0.01, 0.501569),
];

/// What `p2dsetstat` flags mean in afni-core terms. `-2sided` gives AFNI's p
/// directly; `-1sided` doubles it first (except for F, which is never altered),
/// because AFNI stores two-sided p for t/z/correlation. For a *multiple*
/// correlation (nfit > 1) AFNI's "two-sided" p is really the upper tail of R.
fn afni_terms(spec: &StatSpec, flag: &str, p: f64) -> (f64, Tail) {
    let doubled = if flag == "-1sided" && spec.kind != StatKind::Ftest {
        2.0 * p
    } else {
        p
    };
    let tail = match spec.kind {
        StatKind::Ttest | StatKind::Zscore => Tail::TwoSided,
        StatKind::Correl if spec.params[1] == 1.0 => Tail::TwoSided,
        _ => Tail::Upper, // F, and AFNI's multiple correlation
    };
    (doubled, tail)
}

fn volume_spec(name: &str, brick: usize) -> StatSpec {
    // Uses the afni-io fixtures by relative path; this crate must not depend
    // on afni-io, so the specs are written out from the fixtures' headers.
    match (name, brick) {
        ("stat+orig", 0) => StatSpec::new(StatKind::Ttest, &[23.0], 0.0),
        ("stat+orig", 1) => StatSpec::new(StatKind::Ftest, &[2.0, 40.0], 0.0),
        ("correl+orig", 0) => StatSpec::new(StatKind::Correl, &[30.0, 2.0, 1.0], 0.0),
        other => panic!("unknown fixture {other:?}"),
    }
}

#[test]
fn thresholds_match_p2dsetstat_including_multiple_correlation() {
    for &(name, brick, flag, p, expected) in P2DSETSTAT {
        let spec = volume_spec(name, brick);
        let (p_used, tail) = afni_terms(&spec, flag, p);
        let got = critical_value(&spec, p_used, tail).unwrap();
        common::assert_close(
            &format!("{name}[{brick}] {flag} p={p}"),
            got,
            expected,
            Tolerance::SIX_DIGITS,
        );
    }
}

#[test]
fn live_p2dsetstat_agrees_with_the_committed_values() {
    if !common::live_enabled() {
        eprintln!("skipping: set AFNI_CORE_LIVE=1 to run p2dsetstat");
        return;
    }
    let volumes =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../afni-io/tests/data/volume");
    for &(name, brick, flag, p, expected) in P2DSETSTAT {
        let inset = format!("{}[{brick}]", volumes.join(name).display());
        let args: Vec<String> = ["-inset", &inset, "-pval", &p.to_string(), flag, "-quiet"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        let out = common::run_afni("p2dsetstat", &args).expect("p2dsetstat");
        let live: f64 = out
            .trim()
            .parse()
            .unwrap_or_else(|_| panic!("{name}: {out:?}"));
        common::assert_close(
            &format!("live {name}[{brick}] {flag}"),
            live,
            expected,
            Tolerance::SIX_DIGITS,
        );
    }
}
